### ISSUE TITLE
Elastic IP support

### ISSUE THREAD

**Issue by DeviaVir** [pebble/spacel-provision#50]
Without ELB's it would be fairly difficult to continuously reach a certain set of instances. Having EIP support would make this a lot easier.

(also output the EIP(s) after the deploy is done)

**Comment by thepwagner** [comment]
Reuse the pattern from bastion?

**Comment by thepwagner** [comment]
More thinking about this:

If an app is using ElasticIPs, we can harden: https://github.com/pebble/spacel-provision/blob/master/src/spacel/provision/template/ingress_resource.py#L71 so that _only_ that app  is permitted to connect to  service in another region (where the current path allows NAT EIPs, meaning _every_ NAT-ed service in the region). Neato!
