### ISSUE TITLE
Make update policy configurable

### ISSUE THREAD

**Issue by DeviaVir** [pebble/spacel-provision#52]
Currently only `RollingUpdate` with a constant time is available, would be nice if we could make this configurable to red_black/none with configurable timeout (max 60M)

**Comment by thepwagner** [comment]
Default timeouts can be raised too: since spacel-agent signals `FAILURE` when it hits a problem, it's much more likely that we'll fail-fast before the signal timeout is hit (`PT10M` is just nice for moving fast in early dev).


Can we calculate the UpdatePolicy/CreationPolicy timeout based on smaller inputs?
`$containerDownload + $appStartup + ($elbChecks * $elbInterval)` ?

That way the smaller timeouts can be passed to `spacel-agent` to fail faster (i.e. https://github.com/pebble/spacel-agent/blob/master/src/spacel/agent/systemd.py#L17 `max_wait = 2x ($containerDownload + $appStartup)` or so.

**Comment by thepwagner** [comment]
@DeviaVir closed by #64?

**Comment by DeviaVir** [comment]
@thepwagner left open to consider the timeout suggestions you made
